version: 2

defaults:
  - workflow_trigger_on_tags: &workflow_trigger_on_tags
      filters:
        tags:
          only: /.*/

  - run_install_deps: &run_install_deps
      name: Install dependencies
      command: |
        set -ex
        apt-get -q update
        apt-get -qy upgrade
        apt-get -qy install cmake make g++ clang++-8 libglfw3-dev libglew-dev

  - run_build: &run_build
          name: Build
          command: |
            set -ex
            mkdir -p build
            cd build
            cmake .. -G "Unix Makefiles" \
                -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER \
                -DCMAKE_C_COMPILER=$CMAKE_C_COMPILER \
                -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
            make

jobs:

  build_ubuntu1904_clang:
    docker:
      - image: ubuntu:19.04
    environment:
      CMAKE_CXX_COMPILER: "clang++-8"
      CMAKE_C_COMPILER: "clang-8"
      CMAKE_BUILD_TYPE: "Release"
    steps:
      - checkout
      - run: *run_install_deps
      - run: *run_build

  build_ubuntu1904_gcc:
    docker:
      - image: ubuntu:19.04
    environment:
      CMAKE_CXX_COMPILER: "g++-8"
      CMAKE_C_COMPILER: "gcc-8"
      CMAKE_BUILD_TYPE: "Release"
    steps:
      - checkout
      - run: *run_install_deps
      - run: *run_build

workflows:
  version: 2

  main:
    jobs:
      - build_ubuntu1904_clang: *workflow_trigger_on_tags
      - build_ubuntu1904_gcc: *workflow_trigger_on_tags

